# Generated by Django 5.2.7 on 2026-01-19 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="code",
            name="color",
        ),
        migrations.RemoveField(
            model_name="code",
            name="font_family",
        ),
        migrations.RemoveField(
            model_name="code",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="code",
            name="shape_type",
        ),
        migrations.RemoveField(
            model_name="code",
            name="stroke_color",
        ),
        migrations.RemoveField(
            model_name="code",
            name="stroke_width",
        ),
    ]
