# Generated by Django 5.2.7 on 2026-01-26 22:25

from django.db import migrations


TRIGGER_FUNCTION = """
CREATE FUNCTION reference_search_vector_update() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    to_tsvector('english',
      coalesce(NEW.title,'') || ' ' ||
      coalesce(NEW.abstract,'') || ' ' ||
      coalesce(NEW.authors,'') || ' ' ||
      coalesce(NEW.journal,'')
    );
  RETURN NEW;
END
$$ LANGUAGE plpgsql;
"""

TRIGGER = """
CREATE TRIGGER reference_search_vector_trigger
BEFORE INSERT OR UPDATE
ON api_reference
FOR EACH ROW
EXECUTE FUNCTION reference_search_vector_update();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS reference_search_vector_trigger ON api_reference;
"""

DROP_FUNCTION = """
DROP FUNCTION IF EXISTS reference_search_vector_update();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=TRIGGER_FUNCTION + TRIGGER,
            reverse_sql=DROP_TRIGGER + DROP_FUNCTION,
        ),
    ]
