# Generated by Django 5.2.7 on 2026-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
