# Generated by Django 5.2.7 on 2026-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="duplicate_status",
            field=models.CharField(
                choices=[
                    ("Unresolved", "Unresolved"),
                    ("Deleted", "Deleted"),
                    ("Not Duplicate", "Not Duplicate"),
                    ("Resolved", "Resolved"),
                    ("Unique", "Unique"),
                ],
                default="Unique",
                max_length=20,
            ),
        ),
    ]
