# Generated by Django 5.2.7 on 2026-02-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_search_vector_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
