# Generated by Django 5.2.7 on 2026-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="color",
            field=models.CharField(default="#3b82f6", max_length=50),
        ),
    ]
