# Generated by Django 5.2.7 on 2026-02-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_search_vector_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("column_title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free-text", "Free Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("single-select", "Single Select"),
                            ("multi-select", "Multi Select"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.extractionsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_answers",
                        to="api.reference",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.extractionquestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reference", "question"),
                        name="unique_reference_question_answer",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="extractionsection",
            constraint=models.UniqueConstraint(
                fields=("review", "name"), name="unique_review_section_name"
            ),
        ),
    ]
