# Generated by Django 5.2.7 on 2026-01-24 00:01

import django.db.models.deletion
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_code_background_color_remove_code_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=api.models.reference_upload_path)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
    ]
