# Generated by Django 5.2.7 on 2026-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewinvitation",
            name="role",
            field=models.CharField(
                choices=[("Reviewer", "Reviewer"), ("Viewer", "Viewer")],
                default="Viewer",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
