# Generated by Django 5.2.7 on 2026-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_reference_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="prisma_file",
            field=models.FileField(blank=True, null=True, upload_to="prisma_diagrams/"),
        ),
    ]
