# Generated by Django 5.2.7 on 2026-02-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_extractionsection_extractionquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_extraction_completed",
            field=models.BooleanField(default=False),
        ),
    ]
