# Generated by Django 5.2.7 on 2026-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_note_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("Collaborator", "Collaborator"),
                    ("Reviewer", "Reviewer"),
                    ("Viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Collaborator", "Collaborator"),
                    ("Reviewer", "Reviewer"),
                    ("Viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
