# Generated by Django 5.2.7 on 2026-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_review_prisma_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceopinion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
