# Generated by Django 5.2.7 on 2025-10-15 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="date_created",
        ),
    ]
