# Generated by Django 5.2.7 on 2026-01-26 22:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_reference_duplicate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="reference_search_vector_idx"
            ),
        ),
    ]
