# Generated by Django 5.2.7 on 2026-02-08 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_referenceopinion_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referenceopinion",
            options={"ordering": ["-updated_at"]},
        ),
    ]
