# Generated by Django 5.2.7 on 2025-10-16 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_created_at_review_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="is_archived",
            new_name="is_active",
        ),
    ]
