# Generated by Django 5.2.7 on 2026-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_reference_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceduplicatepair",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
