# Generated by Django 5.2.7 on 2026-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_code_highlight_style_alter_code_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referenceopinion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="referenceopinion",
            name="stage",
            field=models.CharField(
                choices=[
                    ("screening", "Screening"),
                    ("full-text", "Full-Text Screening"),
                ],
                default="screening",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referenceopinion",
            unique_together={("reference", "member", "stage")},
        ),
    ]
