# Generated by Django 6.0.2 on 2026-02-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_referenceopinion_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconds", models.IntegerField(default=0)),
                ("sessions", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reviewmember",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member",), name="unique_screening_stat_per_member"
                    )
                ],
            },
        ),
    ]
