# Generated by Django 5.2.7 on 2026-02-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_referenceduplicatepair_resolved"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Inclusive", "Inclusive"),
                            ("Exclusive", "Exclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
    ]
