# Generated by Django 5.2.7 on 2025-10-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_is_archived_review_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
