# Generated by Django 5.2.7 on 2026-02-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_referenceopinion_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="in_extraction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reference",
            name="in_full_text",
            field=models.BooleanField(default=False),
        ),
    ]
