# Generated by Django 6.0.2 on 2026-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_screeningstat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screeningstat",
            name="last_seen",
        ),
    ]
