# Generated by Django 5.2.7 on 2025-10-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_review_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pubblication_types", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=255)),
                ("journal", models.CharField(max_length=255)),
                ("search_methods", models.CharField(max_length=255)),
                ("abstract", models.TextField(blank=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
    ]
