# Generated by Django 5.2.7 on 2026-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_screeningcriteria"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="screeningcriteria",
            constraint=models.UniqueConstraint(
                fields=("review", "name"), name="unique_criteria_per_review"
            ),
        ),
    ]
