# Generated by Django 5.2.7 on 2026-02-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_screeningcriteria_unique_criteria_per_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningcriteria",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
