# Generated by Django 5.2.7 on 2026-02-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_reference_in_extraction_reference_in_full_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="referenceopinion",
            name="reason",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.reason"
            ),
        ),
    ]
