# Generated by Django 5.2.7 on 2025-10-21 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="article_customizations",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
