# Generated by Django 5.2.7 on 2026-02-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_screeningcriteria_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="duplicate_status",
            field=models.CharField(
                choices=[
                    ("Unresolved", "Unresolved"),
                    ("Deleted", "Deleted"),
                    ("Not Duplicate", "Not Duplicate"),
                    ("RESOLVED", "Resolved"),
                    ("UNIQUE", "Unique"),
                ],
                default="UNIQUE",
                max_length=20,
            ),
        ),
    ]
