# Generated by Django 5.2.7 on 2025-10-21 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_reference_article_customizations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="pubblication_types",
            new_name="publication_types",
        ),
    ]
