# Generated by Django 6.0.2 on 2026-02-13 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_user_avatar_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="zotero_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="zotero_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="zotero_api_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="zotero_library_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="zotero_library_type",
            field=models.CharField(
                choices=[("user", "User"), ("group", "Group")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ZoteroSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("push", "Push to Zotero"),
                            ("pull", "Pull from Zotero"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_processed", models.IntegerField(default=0)),
                ("items_with_pdfs", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
