# Generated by Django 5.2.7 on 2025-10-24 01:42
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rename_pubblication_types_reference_publication_types"),
    ]
    operations = [
        CreateExtension("pg_trgm"),
    ]
