# Generated by Django 6.0.2 on 2026-02-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_reference_last_synced_reference_zotero_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="zotero_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("zotero_key__isnull", False)),
                fields=("review", "zotero_key"),
                name="unique_zotero_key_per_review",
            ),
        ),
    ]
