# Generated by Django 5.2.7 on 2026-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_reference_duplicate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="highlight_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text", "Text"),
                    ("area", "Area"),
                    ("freetext", "Free text"),
                    ("image", "Image"),
                    ("drawing", "Drawing"),
                    ("shape", "Shape"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="code",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("highlight", "Highlight"),
                    ("underline", "Underline"),
                    ("strikethrough", "Strikethrough"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
