# Generated by Django 6.0.2 on 2026-02-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_reference_zotero_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="zotero_collection_key",
            field=models.CharField(
                blank=True,
                help_text="Optional: Only sync items from this Zotero collection",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="zotero_collection_name",
            field=models.CharField(
                blank=True,
                help_text="Display name of the selected collection",
                max_length=255,
                null=True,
            ),
        ),
    ]
