# Generated by Django 5.2.7 on 2025-10-24 02:11

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_auto_20251024_0142"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower("title"), "gin_trgm_ops"
                ),
                name="reference_title_trgm_idx",
            ),
        ),
    ]
