# Generated by Django 6.0.2 on 2026-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_review_zotero_collection_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="zotero_collection_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
