# Generated by Django 5.2.7 on 2025-10-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_reference_reference_title_trgm_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceDuplicatePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                (
                    "reference1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reference1",
                        to="api.reference",
                    ),
                ),
                (
                    "reference2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reference2",
                        to="api.reference",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review", "reference1", "reference2"),
                        name="unique_duplicatepair_per_review_refs",
                    )
                ],
            },
        ),
    ]
