# Generated by Django 5.2.7 on 2025-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_referenceduplicatepair"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reference_duplicate_detected",
            field=models.BooleanField(default=False),
        ),
    ]
