# Generated by Django 6.0.2 on 2026-02-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_review_zotero_collection_last_synced"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zoterosynclog",
            options={
                "ordering": ["-synced_at"],
                "verbose_name": "Zotero Sync Log",
                "verbose_name_plural": "Zotero Sync Logs",
            },
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_api_key",
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_collection_key",
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_collection_last_synced",
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_collection_name",
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_library_id",
        ),
        migrations.RemoveField(
            model_name="review",
            name="zotero_library_type",
        ),
        migrations.AddField(
            model_name="zoterosynclog",
            name="library_version",
            field=models.IntegerField(
                blank=True,
                help_text="Zotero library version at time of sync",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ZoteroIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library_id",
                    models.CharField(
                        help_text="Zotero User ID or Group ID", max_length=100
                    ),
                ),
                (
                    "_api_key",
                    models.CharField(
                        db_column="api_key",
                        help_text="Encrypted Zotero API key",
                        max_length=500,
                    ),
                ),
                (
                    "library_type",
                    models.CharField(
                        choices=[
                            ("user", "Personal Library"),
                            ("group", "Group Library"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "collection_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Only sync items from this collection",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the selected collection",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_push_at", models.DateTimeField(blank=True, null=True)),
                ("last_pull_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_version",
                    models.IntegerField(
                        default=0, help_text="Last library version synced"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable Zotero sync for this review",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zotero_integration",
                        to="api.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zotero Integration",
                "verbose_name_plural": "Zotero Integrations",
            },
        ),
    ]
