# Generated by Django 6.0.2 on 2026-02-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_zoterosynclog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceduplicatepair",
            name="auto_resolved",
            field=models.BooleanField(
                default=False, help_text="True if resolved automatically by the system"
            ),
        ),
        migrations.CreateModel(
            name="ReviewChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False, help_text="True if this is a system notification"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data for system messages (e.g., task results)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Review member who sent the message. Null for system messages.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reviewmember",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="api.review",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["review", "created_at"],
                        name="api_reviewc_review__d74bda_idx",
                    ),
                    models.Index(
                        fields=["review", "is_system_message"],
                        name="api_reviewc_review__cd2eab_idx",
                    ),
                ],
            },
        ),
    ]
