# Generated by Django 5.2.7 on 2025-11-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_review_reference_duplicate_detected"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="status",
            field=models.CharField(
                choices=[
                    ("Undecided", "Undecided"),
                    ("Excluded", "Excluded"),
                    ("Maybe", "Maybe"),
                    ("Included", "Included"),
                ],
                default="Undecided",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_inclusive", models.BooleanField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
    ]
