# Generated by Django 5.2.7 on 2025-11-19 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="review",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.review"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborators", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
