# Generated by Django 6.0.2 on 2026-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "00016_create_normalize_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="pages",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
