# Generated by Django 6.0.2 on 2026-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_reference_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionanswer",
            name="value_number",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
