# Generated by Django 5.2.7 on 2025-11-27 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_reviewinvitation_delete_invitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewinvitation",
            name="accepted",
        ),
    ]
