# Generated by Django 5.2.7 on 2025-11-27 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="status",
        ),
        migrations.AddField(
            model_name="review",
            name="is_blinded",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ReferenceOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Undecided", "Undecided"),
                            ("Excluded", "Excluded"),
                            ("Maybe", "Maybe"),
                            ("Included", "Included"),
                        ],
                        default="Undecided",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reference"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("reference", "reviewer")},
            },
        ),
    ]
