# Generated by Django 5.2.7 on 2025-11-28 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_reference_status_review_is_blinded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="api.reference",
            ),
            preserve_default=False,
        ),
    ]
