# Generated by Django 5.2.7 on 2025-11-28 21:38

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_note_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.reference_upload_path
            ),
        ),
    ]
