# Generated by Django 5.2.7 on 2026-01-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_reference_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.JSONField()),
                ("content", models.JSONField()),
                ("comment", models.JSONField(blank=True, null=True)),
                ("color", models.CharField(default="#fff59d", max_length=20)),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reference"
                    ),
                ),
            ],
        ),
    ]
