# Generated by Django 5.2.7 on 2026-01-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_theme_code_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codes",
                to="api.theme",
            ),
        ),
    ]
