# Generated by Django 5.2.7 on 2026-01-15 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_remove_code_theme_code_name_maintheme_subtheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="created_at",
        ),
    ]
