# ---------- Build stage ----------
FROM node:24-alpine AS build

# build args
ARG VITE_API_BASE_URL
ARG VITE_WS_URL

WORKDIR /frontend

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_WS_URL=$VITE_WS_URL \
    pnpm build

# ---------- Final image (optional, can be tiny) ----------
FROM alpine:3.18 AS react-dist
COPY --from=build /frontend/dist /dist
