# ---------- Build stage ----------
FROM node:24-alpine AS build
WORKDIR /frontend

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

# ---------- Final image (optional, can be tiny) ----------
FROM alpine:3.18 AS react-dist
COPY --from=build /frontend/dist /dist
