stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GHCR_REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/$GHCR_USERNAME/$CI_PROJECT_NAME

before_script:
  - echo "$GHCR_TOKEN" | docker login ghcr.io -u $GHCR_USERNAME --password-stdin

build-images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE: ghcr.io/$GHCR_USERNAME/$CI_PROJECT_NAME-django
  script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "ghcr.io": {
            "username": "$GHCR_USERNAME",
            "password": "$GHCR_TOKEN"
          }
        }
      }
      EOF
    - /kaniko/executor
        --context ./backend
        --dockerfile ./backend/Dockerfile
        --destination $IMAGE:latest

deploy-prod:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh docker-cli
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh ubuntu@$EC2_HOST "
        echo '$GHCR_TOKEN' | docker login ghcr.io -u $GHCR_USERNAME --password-stdin &&
        cd /srv/app &&
        docker compose pull &&
        docker compose up -d
      "
  only:
    - main
