# Generated by Django 5.2.11 on 2026-02-19 00:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import slrt_project.references.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_inclusive", models.BooleanField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(default="#3b82f6", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("publication_type", models.CharField(max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("authors", models.TextField()),
                ("journal", models.CharField(max_length=255)),
                ("article_customizations", models.CharField(max_length=255)),
                ("abstract", models.TextField(blank=True)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=slrt_project.references.models.reference_upload_path,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "duplicate_status",
                    models.CharField(
                        choices=[
                            ("Unresolved", "Unresolved"),
                            ("Deleted", "Deleted"),
                            ("Not Duplicate", "Not Duplicate"),
                            ("Resolved", "Resolved"),
                            ("Unique", "Unique"),
                        ],
                        default="Unique",
                        max_length=20,
                    ),
                ),
                ("in_full_text", models.BooleanField(default=False)),
                ("in_extraction", models.BooleanField(default=False)),
                ("is_extraction_completed", models.BooleanField(default=False)),
                ("zotero_key", models.CharField(blank=True, max_length=100, null=True)),
                ("zotero_version", models.IntegerField(default=0)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("pages", models.CharField(blank=True, default="", max_length=50)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reviews.reviewmember",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="reviews.reviewmember",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="references.reference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDuplicatePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "auto_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="True if resolved automatically by the system",
                    ),
                ),
                (
                    "reference1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reference1",
                        to="references.reference",
                    ),
                ),
                (
                    "reference2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reference2",
                        to="references.reference",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_labels",
                        to="references.label",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.reviewmember",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="references.reference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Undecided", "Undecided"),
                            ("Excluded", "Excluded"),
                            ("Maybe", "Maybe"),
                            ("Included", "Included"),
                        ],
                        default="Undecided",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("full-text", "Full-Text Screening"),
                        ],
                        default="screening",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.reviewmember",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="references.reason",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.reference",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="search_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reviews.searchmethod"
            ),
        ),
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=slrt_project.references.models.reference_upload_path
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_label_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceduplicatepair",
            constraint=models.UniqueConstraint(
                fields=("review", "reference1", "reference2"),
                name="unique_duplicatepair_per_review_refs",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencelabel",
            constraint=models.UniqueConstraint(
                fields=("reference", "label"), name="unique_label_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceopinion",
            constraint=models.UniqueConstraint(
                fields=("reference", "member", "stage"), name="unique_reference_opinion"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="reference_search_vector_idx"
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX reference_title_trgm_idx
                ON references_reference
                USING gin (LOWER(title) gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS reference_title_trgm_idx;",
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("zotero_key__isnull", False)),
                fields=("review", "zotero_key"),
                name="unique_zotero_key_per_review",
            ),
        ),
    ]
