# Generated by Django 5.2.11 on 2026-02-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0005_reference_reference_title_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="hotkey",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
