# Generated by Django 5.2.11 on 2026-02-24 22:37

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0008_immutable_unaccent"),
        ("reviews", "0004_alter_review_duplicate_detection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedpdf",
            name="name",
            field=models.CharField(default="file", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadedpdf",
            name="file",
            field=models.FileField(upload_to="uploaded_pdfs/"),
        ),
        migrations.AlterField(
            model_name="uploadedpdf",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_pdfs",
                to="reviews.review",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedpdf",
            index=models.Index(fields=["doi"], name="references__doi_efd9fb_idx"),
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX uploadedpdf_name_trgm 
                ON references_uploadedpdf 
                USING gin (lower(immutable_unaccent(name)) gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS uploadedpdf_name_trgm;",
        ),
    ]
