# Generated by Django 5.2.11 on 2026-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0009_uploadedpdf_doi_uploadedpdf_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedpdf",
            name="name",
            field=models.TextField(),
        ),
    ]
