# Generated by Django 5.2.11 on 2026-02-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0010_alter_uploadedpdf_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedpdf",
            name="file",
            field=models.FileField(max_length=255, upload_to="uploaded_pdfs/"),
        ),
    ]
