# Generated by Django 5.2.11 on 2026-02-25 00:34

from django.db import migrations, models

import slrt_project.references.models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0011_alter_uploadedpdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=slrt_project.references.models.reference_upload_path,
            ),
        ),
    ]
