# Generated by Django 5.2.11 on 2026-02-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0012_alter_reference_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="full_text_status",
            field=models.CharField(blank=True, default="Undecided", max_length=20),
        ),
        migrations.AddField(
            model_name="reference",
            name="screening_status",
            field=models.CharField(blank=True, default="Undecided", max_length=20),
        ),
    ]
