# Generated by Django 5.2.11 on 2026-03-01 16:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0013_reference_full_text_status_and_more"),
        ("reviews", "0004_alter_review_duplicate_detection_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("auto_resolved", "Auto-Resolved"),
                            ("manually_resolved", "Manually Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="unresolved",
                        max_length=30,
                    ),
                ),
                ("max_similarity_score", models.FloatField(default=0.0)),
                ("doi_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "canonical_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_in_clusters",
                        to="references.reference",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_clusters",
                        to="reviews.reviewmember",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_clusters",
                        to="reviews.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceClusterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("canonical", "Canonical (kept)"),
                            ("duplicate", "Duplicate (removed)"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("best_similarity_score", models.FloatField(default=0.0)),
                ("doi_matched", models.BooleanField(default=False)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="references.referencecluster",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="references.reference",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="referencecluster",
            index=models.Index(
                fields=["review", "status"], name="references__review__1ba8ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencecluster",
            index=models.Index(
                fields=["review", "doi_match"], name="references__review__ee2092_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referenceclustermember",
            index=models.Index(
                fields=["reference", "role"], name="references__referen_b55be1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceclustermember",
            constraint=models.UniqueConstraint(
                fields=("cluster", "reference"), name="unique_reference_per_cluster"
            ),
        ),
    ]
