# Generated by Django 5.2.11 on 2026-03-01 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0014_referencecluster_referenceclustermember_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReferenceDuplicatePair",
        ),
    ]
