# Generated by Django 5.2.11 on 2026-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0015_delete_referenceduplicatepair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="is_inclusive",
        ),
        migrations.AddField(
            model_name="keyword",
            name="type",
            field=models.CharField(
                choices=[("inclusion", "Inclusion"), ("exclusion", "Exclusion")],
                default="inclusion",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
