# Generated by Django 5.2.11 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0016_remove_keyword_is_inclusive_keyword_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="duplicate_status",
            field=models.CharField(
                choices=[
                    ("unresolved", "Unresolved"),
                    ("detected", "Deleted"),
                    ("not_duplicate", "Not Duplicate"),
                    ("resolved", "Resolved"),
                    ("unique", "Unique"),
                ],
                default="unique",
                max_length=20,
            ),
        ),
    ]
