# Generated by Django 5.2.11 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0018_alter_reference_duplicate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="full_text_status",
            field=models.CharField(blank=True, default="undecided", max_length=20),
        ),
        migrations.AlterField(
            model_name="reference",
            name="screening_status",
            field=models.CharField(blank=True, default="undecided", max_length=20),
        ),
        migrations.AlterField(
            model_name="referenceopinion",
            name="status",
            field=models.CharField(
                choices=[
                    ("undecided", "Undecided"),
                    ("excluded", "Excluded"),
                    ("maybe", "Maybe"),
                    ("included", "Included"),
                ],
                default="undecided",
                max_length=20,
            ),
        ),
    ]
