import factory
from factory import LazyAttribute, Sequence, SubFactory, Trait
from factory.django import DjangoModelFactory

from slrt_project.coding.models import Code, MainTheme, SubTheme
from slrt_project.references.tests.factories import ReferenceFactory
from slrt_project.reviews.tests.factories import ReviewMemberFactory


# MainThemeFactory
class MainThemeFactory(DjangoModelFactory):
    """
    Creates a MainTheme with a unique name per sequence counter.
    """

    class Meta:
        model = MainTheme

    # A single ReviewMember provides both the member FK and the review FK,
    # guaranteeing they always point to the same review.
    member = SubFactory(ReviewMemberFactory)
    review = LazyAttribute(lambda o: o.member.review)

    # Sequence ensures uniqueness within a test session.
    name = Sequence(lambda n: f"Main Theme {n}")
    description = ""


# SubThemeFactory
class SubThemeFactory(DjangoModelFactory):
    """
    Creates a SubTheme, optionally nested under a MainTheme.
    """

    class Meta:
        model = SubTheme

    member = SubFactory(ReviewMemberFactory)
    review = LazyAttribute(lambda o: o.member.review)
    name = Sequence(lambda n: f"Sub Theme {n}")
    description = ""

    # Default: create a parent MainTheme in the same review/member.
    main_theme = SubFactory(
        MainThemeFactory,
        member=LazyAttribute(lambda o: o.factory_parent.member),
        review=LazyAttribute(lambda o: o.factory_parent.review),
    )


# CodeFactory
class CodeFactory(DjangoModelFactory):
    """
    Creates a Code with a TEXT highlight type by default.
    """

    class Meta:
        model = Code

    # UUIDs are generated by the model default; no need to set id explicitly.

    member = SubFactory(ReviewMemberFactory)
    review = LazyAttribute(lambda o: o.member.review)
    reference = SubFactory(ReferenceFactory)
    sub_theme = SubFactory(
        SubThemeFactory,
        member=LazyAttribute(lambda o: o.factory_parent.member),
        review=LazyAttribute(lambda o: o.factory_parent.review),
    )

    name = Sequence(lambda n: f"Code {n}")
    type = Code.HighlightType.TEXT

    # react-pdf-highlighter payloads — a minimal but realistic structure.
    content = factory.LazyFunction(lambda: {"text": "sample highlighted text"})
    position = factory.LazyFunction(
        lambda: {
            "boundingRect": {
                "x1": 0,
                "y1": 0,
                "x2": 100,
                "y2": 20,
                "width": 800,
                "height": 1000,
            },
            "rects": [
                {"x1": 0, "y1": 0, "x2": 100, "y2": 20, "width": 800, "height": 1000}
            ],
            "pageNumber": 1,
        }
    )

    comment = None
    highlight_color = "#FFFF00"
    highlight_style = Code.HighlightStyle.HIGHLIGHT

    class Params:
        text = Trait(
            type=Code.HighlightType.TEXT,
            highlight_color="#FFFF00",
            highlight_style=Code.HighlightStyle.HIGHLIGHT,
        )
        area = Trait(
            type=Code.HighlightType.AREA,
            highlight_color="#ADD8E6",
            highlight_style=Code.HighlightStyle.HIGHLIGHT,
        )
        freetext = Trait(
            type=Code.HighlightType.FREETEXT,
            content=None,
            position=None,
            highlight_color=None,
            highlight_style=None,
        )
        image = Trait(
            type=Code.HighlightType.IMAGE,
            content=factory.LazyFunction(
                lambda: {"image": "data:image/png;base64,abc="}
            ),
            highlight_color=None,
            highlight_style=None,
        )
        drawing = Trait(
            type=Code.HighlightType.DRAWING,
            highlight_color=None,
            highlight_style=None,
        )
        shape = Trait(
            type=Code.HighlightType.SHAPE,
            highlight_color=None,
            highlight_style=None,
        )
