# Generated by Django 5.2.11 on 2026-02-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoteroIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library_id",
                    models.CharField(
                        help_text="Zotero User ID or Group ID", max_length=100
                    ),
                ),
                (
                    "_api_key",
                    models.CharField(
                        db_column="api_key",
                        help_text="Encrypted Zotero API key",
                        max_length=500,
                    ),
                ),
                (
                    "library_type",
                    models.CharField(
                        choices=[
                            ("user", "Personal Library"),
                            ("group", "Group Library"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "collection_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Only sync items from this collection",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the selected collection",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_push_at", models.DateTimeField(blank=True, null=True)),
                ("last_pull_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_version",
                    models.IntegerField(
                        default=0, help_text="Last library version synced"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable Zotero sync for this review",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zotero_integration",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zotero Integration",
                "verbose_name_plural": "Zotero Integrations",
            },
        ),
        migrations.CreateModel(
            name="ZoteroSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("push", "Push to Zotero"),
                            ("pull", "Pull from Zotero"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_processed", models.IntegerField(default=0)),
                ("items_with_pdfs", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "library_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Zotero library version at time of sync",
                        null=True,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zotero Sync Log",
                "verbose_name_plural": "Zotero Sync Logs",
                "ordering": ["-synced_at"],
            },
        ),
    ]
