# Generated by Django 5.2.11 on 2026-02-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reference_duplicate_detected", models.BooleanField(default=False)),
                ("is_blinded", models.BooleanField(default=True)),
                (
                    "prisma_file",
                    models.FileField(
                        blank=True, null=True, upload_to="prisma_diagrams/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Collaborator", "Collaborator"),
                            ("Reviewer", "Reviewer"),
                            ("Viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Reviewer", "Reviewer"),
                            ("Viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="reviews.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False, help_text="True if this is a system notification"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data for system messages (e.g., task results)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="reviews.review",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Review member who sent the message. Null for system messages.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.reviewmember",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Inclusive", "Inclusive"),
                            ("Exclusive", "Exclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconds", models.IntegerField(default=0)),
                ("sessions", models.IntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.reviewmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.review"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reviewmember",
            constraint=models.UniqueConstraint(
                fields=("review", "user"), name="unique_user_per_review"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewchatmessage",
            index=models.Index(
                fields=["review", "created_at"], name="reviews_rev_review__aea185_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewchatmessage",
            index=models.Index(
                fields=["review", "is_system_message"],
                name="reviews_rev_review__45f2bf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="screeningcriteria",
            constraint=models.UniqueConstraint(
                fields=("review", "name"), name="unique_criteria_per_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="screeningstat",
            constraint=models.UniqueConstraint(
                fields=("member",), name="unique_screening_stat_per_member"
            ),
        ),
    ]
