# Generated by Django 5.2.11 on 2026-02-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchmethod",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded BibTeX file (deleted after successful import)",
                null=True,
                upload_to="bibtex_uploads/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="searchmethod",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="searchmethod",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
