# Generated by Django 5.2.11 on 2026-02-22 00:12

from django.db import migrations, models

import slrt_project.reviews.models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_searchmethod_file_searchmethod_import_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="reference_duplicate_detected",
        ),
        migrations.RemoveField(
            model_name="searchmethod",
            name="import_status",
        ),
        migrations.RemoveField(
            model_name="searchmethod",
            name="imported_at",
        ),
        migrations.AddField(
            model_name="review",
            name="duplicate_detection_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="searchmethod",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded BibTeX file (deleted after successful import)",
                null=True,
                upload_to=slrt_project.reviews.models.search_method_upload_path,
            ),
        ),
    ]
