# Generated by Django 5.2.11 on 2026-02-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_remove_review_reference_duplicate_detected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="duplicate_detection_status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                ],
                default="Not Started",
                max_length=20,
            ),
        ),
    ]
