# Generated by Django 5.2.11 on 2026-03-03 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_alter_review_duplicate_detection_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screeningcriteria",
            old_name="kind",
            new_name="type",
        ),
    ]
