# Generated by Django 5.2.11 on 2026-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_rename_kind_screeningcriteria_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningcriteria",
            name="type",
            field=models.CharField(
                choices=[("inclusion", "Inclusion"), ("exclusion", "Exclusion")],
                max_length=20,
            ),
        ),
    ]
