# Generated by Django 5.2.11 on 2026-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_alter_screeningcriteria_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("collaborator", "Collaborator"),
                    ("reviewer", "Reviewer"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
