# Generated by Django 5.2.11 on 2026-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_alter_reviewmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("collaborator", "Collaborator"),
                    ("reviewer", "Reviewer"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
