# Generated by Django 5.2.11 on 2026-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0008_alter_reviewinvitation_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="duplicate_detection_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
