/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestPasswordResetRouteImport } from './routes/request-password-reset'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as ConfirmPasswordResetRouteImport } from './routes/confirm-password-reset'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsReviewIdIndexRouteImport } from './routes/reviews/$reviewId/index'
import { Route as ReviewsReviewIdScreeningRouteImport } from './routes/reviews/$reviewId/screening'
import { Route as ReviewsReviewIdReviewDataRouteImport } from './routes/reviews/$reviewId/review-data'
import { Route as ReviewsReviewIdPrismaRouteImport } from './routes/reviews/$reviewId/prisma'
import { Route as ReviewsReviewIdFullTextScreeningRouteImport } from './routes/reviews/$reviewId/full-text-screening'
import { Route as ReviewsReviewIdDataExtractionRouteImport } from './routes/reviews/$reviewId/data-extraction'
import { Route as ReviewsReviewIdCodingThemingRouteImport } from './routes/reviews/$reviewId/coding-theming'
import { Route as ReviewsReviewId_layoutRouteImport } from './routes/reviews/$reviewId/__layout'

const ReviewsReviewIdRouteImport = createFileRoute('/reviews/$reviewId')()

const RequestPasswordResetRoute = RequestPasswordResetRouteImport.update({
  id: '/request-password-reset',
  path: '/request-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmPasswordResetRoute = ConfirmPasswordResetRouteImport.update({
  id: '/confirm-password-reset',
  path: '/confirm-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdIndexRoute = ReviewsReviewIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsReviewIdRoute,
} as any)
const ReviewsReviewIdScreeningRoute =
  ReviewsReviewIdScreeningRouteImport.update({
    id: '/screening',
    path: '/screening',
    getParentRoute: () => ReviewsReviewIdRoute,
  } as any)
const ReviewsReviewIdReviewDataRoute =
  ReviewsReviewIdReviewDataRouteImport.update({
    id: '/review-data',
    path: '/review-data',
    getParentRoute: () => ReviewsReviewIdRoute,
  } as any)
const ReviewsReviewIdPrismaRoute = ReviewsReviewIdPrismaRouteImport.update({
  id: '/prisma',
  path: '/prisma',
  getParentRoute: () => ReviewsReviewIdRoute,
} as any)
const ReviewsReviewIdFullTextScreeningRoute =
  ReviewsReviewIdFullTextScreeningRouteImport.update({
    id: '/full-text-screening',
    path: '/full-text-screening',
    getParentRoute: () => ReviewsReviewIdRoute,
  } as any)
const ReviewsReviewIdDataExtractionRoute =
  ReviewsReviewIdDataExtractionRouteImport.update({
    id: '/data-extraction',
    path: '/data-extraction',
    getParentRoute: () => ReviewsReviewIdRoute,
  } as any)
const ReviewsReviewIdCodingThemingRoute =
  ReviewsReviewIdCodingThemingRouteImport.update({
    id: '/coding-theming',
    path: '/coding-theming',
    getParentRoute: () => ReviewsReviewIdRoute,
  } as any)
const ReviewsReviewId_layoutRoute = ReviewsReviewId_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => ReviewsReviewIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/confirm-password-reset': typeof ConfirmPasswordResetRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reviews/$reviewId': typeof ReviewsReviewId_layoutRoute
  '/reviews/$reviewId/coding-theming': typeof ReviewsReviewIdCodingThemingRoute
  '/reviews/$reviewId/data-extraction': typeof ReviewsReviewIdDataExtractionRoute
  '/reviews/$reviewId/full-text-screening': typeof ReviewsReviewIdFullTextScreeningRoute
  '/reviews/$reviewId/prisma': typeof ReviewsReviewIdPrismaRoute
  '/reviews/$reviewId/review-data': typeof ReviewsReviewIdReviewDataRoute
  '/reviews/$reviewId/screening': typeof ReviewsReviewIdScreeningRoute
  '/reviews/$reviewId/': typeof ReviewsReviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/confirm-password-reset': typeof ConfirmPasswordResetRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdIndexRoute
  '/reviews/$reviewId/coding-theming': typeof ReviewsReviewIdCodingThemingRoute
  '/reviews/$reviewId/data-extraction': typeof ReviewsReviewIdDataExtractionRoute
  '/reviews/$reviewId/full-text-screening': typeof ReviewsReviewIdFullTextScreeningRoute
  '/reviews/$reviewId/prisma': typeof ReviewsReviewIdPrismaRoute
  '/reviews/$reviewId/review-data': typeof ReviewsReviewIdReviewDataRoute
  '/reviews/$reviewId/screening': typeof ReviewsReviewIdScreeningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/confirm-password-reset': typeof ConfirmPasswordResetRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/request-password-reset': typeof RequestPasswordResetRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRouteWithChildren
  '/reviews/$reviewId/__layout': typeof ReviewsReviewId_layoutRoute
  '/reviews/$reviewId/coding-theming': typeof ReviewsReviewIdCodingThemingRoute
  '/reviews/$reviewId/data-extraction': typeof ReviewsReviewIdDataExtractionRoute
  '/reviews/$reviewId/full-text-screening': typeof ReviewsReviewIdFullTextScreeningRoute
  '/reviews/$reviewId/prisma': typeof ReviewsReviewIdPrismaRoute
  '/reviews/$reviewId/review-data': typeof ReviewsReviewIdReviewDataRoute
  '/reviews/$reviewId/screening': typeof ReviewsReviewIdScreeningRoute
  '/reviews/$reviewId/': typeof ReviewsReviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/confirm-password-reset'
    | '/edit-profile'
    | '/login'
    | '/register'
    | '/request-password-reset'
    | '/reviews/$reviewId'
    | '/reviews/$reviewId/coding-theming'
    | '/reviews/$reviewId/data-extraction'
    | '/reviews/$reviewId/full-text-screening'
    | '/reviews/$reviewId/prisma'
    | '/reviews/$reviewId/review-data'
    | '/reviews/$reviewId/screening'
    | '/reviews/$reviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/confirm-password-reset'
    | '/edit-profile'
    | '/login'
    | '/register'
    | '/request-password-reset'
    | '/reviews/$reviewId'
    | '/reviews/$reviewId/coding-theming'
    | '/reviews/$reviewId/data-extraction'
    | '/reviews/$reviewId/full-text-screening'
    | '/reviews/$reviewId/prisma'
    | '/reviews/$reviewId/review-data'
    | '/reviews/$reviewId/screening'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/confirm-password-reset'
    | '/edit-profile'
    | '/login'
    | '/register'
    | '/request-password-reset'
    | '/reviews/$reviewId'
    | '/reviews/$reviewId/__layout'
    | '/reviews/$reviewId/coding-theming'
    | '/reviews/$reviewId/data-extraction'
    | '/reviews/$reviewId/full-text-screening'
    | '/reviews/$reviewId/prisma'
    | '/reviews/$reviewId/review-data'
    | '/reviews/$reviewId/screening'
    | '/reviews/$reviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConfirmPasswordResetRoute: typeof ConfirmPasswordResetRoute
  EditProfileRoute: typeof EditProfileRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RequestPasswordResetRoute: typeof RequestPasswordResetRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-password-reset': {
      id: '/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/request-password-reset'
      preLoaderRoute: typeof RequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-password-reset': {
      id: '/confirm-password-reset'
      path: '/confirm-password-reset'
      fullPath: '/confirm-password-reset'
      preLoaderRoute: typeof ConfirmPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId/': {
      id: '/reviews/$reviewId/'
      path: '/'
      fullPath: '/reviews/$reviewId/'
      preLoaderRoute: typeof ReviewsReviewIdIndexRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/screening': {
      id: '/reviews/$reviewId/screening'
      path: '/screening'
      fullPath: '/reviews/$reviewId/screening'
      preLoaderRoute: typeof ReviewsReviewIdScreeningRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/review-data': {
      id: '/reviews/$reviewId/review-data'
      path: '/review-data'
      fullPath: '/reviews/$reviewId/review-data'
      preLoaderRoute: typeof ReviewsReviewIdReviewDataRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/prisma': {
      id: '/reviews/$reviewId/prisma'
      path: '/prisma'
      fullPath: '/reviews/$reviewId/prisma'
      preLoaderRoute: typeof ReviewsReviewIdPrismaRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/full-text-screening': {
      id: '/reviews/$reviewId/full-text-screening'
      path: '/full-text-screening'
      fullPath: '/reviews/$reviewId/full-text-screening'
      preLoaderRoute: typeof ReviewsReviewIdFullTextScreeningRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/data-extraction': {
      id: '/reviews/$reviewId/data-extraction'
      path: '/data-extraction'
      fullPath: '/reviews/$reviewId/data-extraction'
      preLoaderRoute: typeof ReviewsReviewIdDataExtractionRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/coding-theming': {
      id: '/reviews/$reviewId/coding-theming'
      path: '/coding-theming'
      fullPath: '/reviews/$reviewId/coding-theming'
      preLoaderRoute: typeof ReviewsReviewIdCodingThemingRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
    '/reviews/$reviewId/__layout': {
      id: '/reviews/$reviewId/__layout'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewId_layoutRouteImport
      parentRoute: typeof ReviewsReviewIdRoute
    }
  }
}

interface ReviewsReviewIdRouteChildren {
  ReviewsReviewId_layoutRoute: typeof ReviewsReviewId_layoutRoute
  ReviewsReviewIdCodingThemingRoute: typeof ReviewsReviewIdCodingThemingRoute
  ReviewsReviewIdDataExtractionRoute: typeof ReviewsReviewIdDataExtractionRoute
  ReviewsReviewIdFullTextScreeningRoute: typeof ReviewsReviewIdFullTextScreeningRoute
  ReviewsReviewIdPrismaRoute: typeof ReviewsReviewIdPrismaRoute
  ReviewsReviewIdReviewDataRoute: typeof ReviewsReviewIdReviewDataRoute
  ReviewsReviewIdScreeningRoute: typeof ReviewsReviewIdScreeningRoute
  ReviewsReviewIdIndexRoute: typeof ReviewsReviewIdIndexRoute
}

const ReviewsReviewIdRouteChildren: ReviewsReviewIdRouteChildren = {
  ReviewsReviewId_layoutRoute: ReviewsReviewId_layoutRoute,
  ReviewsReviewIdCodingThemingRoute: ReviewsReviewIdCodingThemingRoute,
  ReviewsReviewIdDataExtractionRoute: ReviewsReviewIdDataExtractionRoute,
  ReviewsReviewIdFullTextScreeningRoute: ReviewsReviewIdFullTextScreeningRoute,
  ReviewsReviewIdPrismaRoute: ReviewsReviewIdPrismaRoute,
  ReviewsReviewIdReviewDataRoute: ReviewsReviewIdReviewDataRoute,
  ReviewsReviewIdScreeningRoute: ReviewsReviewIdScreeningRoute,
  ReviewsReviewIdIndexRoute: ReviewsReviewIdIndexRoute,
}

const ReviewsReviewIdRouteWithChildren = ReviewsReviewIdRoute._addFileChildren(
  ReviewsReviewIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConfirmPasswordResetRoute: ConfirmPasswordResetRoute,
  EditProfileRoute: EditProfileRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RequestPasswordResetRoute: RequestPasswordResetRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
